PINECONE_API_KEY = "pcsk_7VKnjP_M3VsCK1KrNrwQwyDQXVm6gfojM44VzcgEkYCrmrLurVBmAGTTAK9nzf77Bsgw7T"
AZURE_OPENAI_API_KEY = "f1e1256d93cf4ff5ad7f63b54cf6e910"
AZURE_OPENAI_API_VERSION = "2024-02-15-preview"
AZURE_OPENAI_ENDPOINT = "https://ai-tucuviusgenai017017663638.openai.azure.com"
GOOGLE_CLIENT_ID = "457348507475-qj2rs65seoc2dmecc2ldhmal1ur3ifqm.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI_LOCAL = "http://localhost:8501"
REDIRECT_URI = "https://chat-tucuvi-data.streamlit.app"